var dir_c5a52a81292cf9a5167198f4f346d6d9 =
[
    [ "bluey_1v1.h", "bluey__1v1_8h_source.html", null ],
    [ "boards.h", "boards_8h_source.html", null ],
    [ "detect_rev1.h", "detect__rev1_8h_source.html", null ],
    [ "hackable.h", "hackable_8h_source.html", null ],
    [ "papyr_rev03.h", "papyr__rev03_8h_source.html", null ],
    [ "pca10028.h", "pca10028_8h_source.html", null ],
    [ "pca10040.h", "pca10040_8h_source.html", null ],
    [ "sensebe_rev1.h", "sensebe__rev1_8h_source.html", null ],
    [ "sensebe_rev3.h", "sensebe__rev3_8h_source.html", null ],
    [ "sensebe_rx_rev1.h", "sensebe__rx__rev1_8h_source.html", null ],
    [ "sensebe_rx_rev2.h", "sensebe__rx__rev2_8h_source.html", null ],
    [ "senseberx_rev3.h", "senseberx__rev3_8h_source.html", null ],
    [ "senseberx_rev4.h", "senseberx__rev4_8h_source.html", null ],
    [ "sensebetx_rev3.h", "sensebetx__rev3_8h_source.html", null ],
    [ "sensebetx_rev4.h", "sensebetx__rev4_8h_source.html", null ],
    [ "senseble_rev1.h", "senseble__rev1_8h_source.html", null ],
    [ "senseele_pcb_rev1.h", "senseele__pcb__rev1_8h_source.html", null ],
    [ "senseele_pcb_rev2.h", "senseele__pcb__rev2_8h_source.html", null ],
    [ "senseele_sma_rev1.h", "senseele__sma__rev1_8h_source.html", null ],
    [ "sensepi_rev2.h", "sensepi__rev2_8h_source.html", null ],
    [ "sensepi_rev3.h", "sensepi__rev3_8h_source.html", null ],
    [ "sensepi_rev4.h", "sensepi__rev4_8h_source.html", null ],
    [ "sensepi_rev5.h", "sensepi__rev5_8h_source.html", null ]
];