Appiko: PIR Sense
PIR Sense
Codebase » Peripheral Modules
Driver use detect motion based on threshold from a PIR sensor based on PPI based automated ADC sampling of the PIR signal from the triggering of a RTC timer.
Data Structures
struct pir_sense_cfg
Stucture for passing the configuration for initializing the PIR Sense module.
Enumerations
enum pir_sense_clk_t { PIR_SENSE_LF_CLK = AUX_CLK_SRC_LFCLK, PIR_SENSE_HF_CLK = AUX_CLK_SRC_HFCLK }
Functions
void pir_sense_start (pir_sense_cfg *init)
void pir_sense_stop (void)
Disable the peripherals involved - SAADC, PPIs and RTC0.
void pir_sense_update_threshold (uint32_t threshold)
Function to update threshold for PIR sensing.
void pir_sense_switch_clock (pir_sense_clk_t clk_src)
Function to switch to given clock source.
Detailed Description
The image below gives the flow of how the peripherals of nRF52 is setup for this application.
Warning
This module needs the LFCLK to be on and running to be able to work
This module uses RTC0, which is used by Softdevice. So this module will not work with a Softdevice.
Enumeration Type Documentation
pir_sense_clk_t
enum pir_sense_clk_t
List of Clock Sources that can be used to drive this module
Enumerator
PIR_SENSE_LF_CLK
Low freq clock : low power mode
PIR_SENSE_HF_CLK
High freq clock : high power mode
Definition at line 94 of file pir_sense.h.
Function Documentation
pir_sense_start()
void pir_sense_start (pir_sense_cfg * init)
Initialize and start the PIR Sense module based on the configuration received
Parameters
init Initialization configuration pointer
Definition at line 59 of file pir_sense.c.
pir_sense_stop()
void pir_sense_stop (void)
Deinitializes, stops the PIR Sense module and frees the peripherals used by it
Definition at line 160 of file pir_sense.c.
References aux_clk_clear(), aux_clk_dis_ppi_ch(), aux_clk_stop(), hal_ppi_dis_ch(), PPI_CHANNEL_USED_PIR_SENSE_1, PPI_CHANNEL_USED_PIR_SENSE_2, and PPI_CHANNEL_USED_PIR_SENSE_3.
pir_sense_switch_clock()
void pir_sense_switch_clock (pir_sense_clk_t clk_src)
Parameters
clk_src clock source which is to be used
Definition at line 191 of file pir_sense.c.
References aux_clk_select_src().
pir_sense_update_threshold()
void pir_sense_update_threshold (uint32_t threshold)
Parameters
threshold Updated value for threshold.
Definition at line 182 of file pir_sense.c.