Appiko: SIM800 Command IDs
SIM800 Command IDs
Codebase » AT Library
List of all the command IDs required for SIM800 operation.
Data Structures
struct sim800_server_conn_t
struct sim800_http_req_t
struct sim800_init_t
Macros
#define SIM800_MOD_CMD_BASE (0x0000)
#define SIM800_NET_CMD_BASE (0x1000)
#define SIM800_HTTP_CMD_BASE (0x2000)
#define SIM800_NORMAL_CMD_BASE (0x000)
#define SIM800_CRITICAL_CMD_BASE (0x100)
#define SIM800_INFO_CMD_BASE (0x200)
#define IS_CMD_CRITICAL(x) ((x & SIM800_CRITICAL_CMD_BASE) >> 8)
#define IS_RSP_VARIABLE(x) ((x & SIM800_INFO_CMD_BASE) >> 9)
Enumerations
enum SIM800_MOD_CMD {
SIM800_MOD_INIT = (SIM800_MOD_CMD_BASE+SIM800_CRITICAL_CMD_BASE+1), SIM800_MOD_FCT_RST = (SIM800_MOD_CMD_BASE+SIM800_NORMAL_CMD_BASE+2), SIM800_MOD_TIME_FMT = (SIM800_MOD_CMD_BASE+SIM800_NORMAL_CMD_BASE+3), SIM800_MOD_SAVE_NVM = (SIM800_MOD_CMD_BASE+SIM800_NORMAL_CMD_BASE+4),
SIM800_MOD_DIS_FUNC = (SIM800_MOD_CMD_BASE+SIM800_NORMAL_CMD_BASE+5), SIM800_MOD_EN_FUNC = (SIM800_MOD_CMD_BASE+SIM800_NORMAL_CMD_BASE+6), SIM800_MOD_CHK_SIM = (SIM800_MOD_CMD_BASE+SIM800_CRITICAL_CMD_BASE+7), SIM800_MOD_ECHO_OFF = (SIM800_MOD_CMD_BASE+SIM800_NORMAL_CMD_BASE+8)
}
enum SIM800_NET_CMD {
SIM800_NET_CRT_CHK = (SIM800_NET_CMD_BASE+SIM800_CRITICAL_CMD_BASE+1), SIM800_NET_BSET_CTYPE = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+2), SIM800_NET_BSET_APN = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+3), SIM800_NET_BSET_USR = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+4),
SIM800_NET_BSET_PWD = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+5), SIM800_NET_BEN = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+6), SIM800_NET_BCHK = (SIM800_NET_CMD_BASE+SIM800_INFO_CMD_BASE+7), SIM800_NET_PDP_CNTX = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+8),
SIM800_NET_ACTV_CID = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+9), SIM800_NET_EN_MUX = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+10), SIM800_NET_SEL_DTX = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+11), SIM800_NET_TSK_START = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+12),
SIM800_NET_EN_GPRS = (SIM800_NET_CMD_BASE+SIM800_CRITICAL_CMD_BASE+13), SIM800_NET_GET_IP = (SIM800_NET_CMD_BASE+SIM800_INFO_CMD_BASE+14), SIM800_NET_CHK = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+15), SIM800_NET_CHK_GPRS = (SIM800_NET_CMD_BASE+SIM800_NORMAL_CMD_BASE+16)
}
enum SIM800_HTTP_CMD {
SIM800_HTTP_INIT = (SIM800_HTTP_CMD_BASE+SIM800_NORMAL_CMD_BASE+1), SIM800_HTTP_PARA_CID = (SIM800_HTTP_CMD_BASE+SIM800_NORMAL_CMD_BASE+2), SIM800_HTTP_PARA_URL = (SIM800_HTTP_CMD_BASE+SIM800_NORMAL_CMD_BASE+3), SIM800_HTTP_PARA_CTYPE = (SIM800_HTTP_CMD_BASE+SIM800_NORMAL_CMD_BASE+4),
SIM800_HTTP_RQST_GET = (SIM800_HTTP_CMD_BASE+SIM800_INFO_CMD_BASE+5), SIM800_HTTP_RQST_POST = (SIM800_HTTP_CMD_BASE+SIM800_INFO_CMD_BASE+6), SIM800_HTTP_DATA_READ = (SIM800_HTTP_CMD_BASE+SIM800_INFO_CMD_BASE+7), SIM800_HTTP_DATA_SEND = (SIM800_HTTP_CMD_BASE+SIM800_INFO_CMD_BASE+8)
}
enum sim800_oper_status_t {
SIM800_IDLE, SIM800_BUSY, SIM800_HALT, SIM800_OVERLOAD,
SIM800_NOT_FOUND
}
enum sim800_conn_status_t { SIM800_DISCONNECTED, SIM800_CONNECTED }
enum sim800_operator_t
enum sim800_oper_http_contn_typ_t { SIM800_HTTP_CONTENT_PTXT, SIM800_HTTP_CONTENT_RTXT, SIM800_HTTP_CONTENT_OCT_S }
enum sim800_req_type_t
Functions
void sim800_oper_init (sim800_init_t *init)
Function to initialize basic operations of sim800 module.
void sim800_oper_process ()
Function to process SIM800 operations.
void sim800_oper_add_ticks (uint32_t ticks)
Function to handle add ticks event for sim800 operation module.
sim800_oper_status_t sim800_oper_get_status ()
Function to get current state of sim800 module.
void sim800_oper_enable_gprs (uint8_t *ip_addr, uint32_t *len)
Function to enable GPRS service.
void sim800_oper_conns (sim800_server_conn_t *conn_params)
Function to connect to a server.
void sim800_oper_http_req (sim800_http_req_t *http_req)
Function to generate http request.
sim800_conn_status_t sim800_oper_get_gprs_status ()
Function to get gprs_status.
Detailed Description
Driver to use SIM800 module using the AT Process.
Warning
This module needs the device_tick to be on and running to be able to work
Macro Definition Documentation
IS_CMD_CRITICAL
#define IS_CMD_CRITICAL (x) ((x & SIM800_CRITICAL_CMD_BASE) >> 8)
Macro to check if command is critical
Definition at line 55 of file sim800_cmd_id.h.
Referenced by sim800_oper_enable_gprs(), and sim800_oper_http_req().
IS_RSP_VARIABLE
#define IS_RSP_VARIABLE (x) ((x & SIM800_INFO_CMD_BASE) >> 9)
Macro to check if variable response is expected
Definition at line 57 of file sim800_cmd_id.h.
Referenced by sim800_oper_enable_gprs(), and sim800_oper_http_req().
SIM800_CRITICAL_CMD_BASE
#define SIM800_CRITICAL_CMD_BASE (0x100)
Base value for commands which has definite responses, errors and is critical
Definition at line 50 of file sim800_cmd_id.h.
SIM800_HTTP_CMD_BASE
#define SIM800_HTTP_CMD_BASE (0x2000)
Base value for HTTP related commands
Definition at line 44 of file sim800_cmd_id.h.
SIM800_INFO_CMD_BASE
#define SIM800_INFO_CMD_BASE (0x200)
Base value for commands which has variable response
Definition at line 52 of file sim800_cmd_id.h.
SIM800_MOD_CMD_BASE
#define SIM800_MOD_CMD_BASE (0x0000)
Primary Base Base value for Module related commands
Definition at line 40 of file sim800_cmd_id.h.
SIM800_NET_CMD_BASE
#define SIM800_NET_CMD_BASE (0x1000)
Base value for network related commands
Definition at line 42 of file sim800_cmd_id.h.
SIM800_NORMAL_CMD_BASE
#define SIM800_NORMAL_CMD_BASE (0x000)
Secondary Base Base value for commands which has definite responses, errors and isn't critical
Definition at line 48 of file sim800_cmd_id.h.
Enumeration Type Documentation
sim800_conn_status_t
enum sim800_conn_status_t
State of any network or server connection
Enumerator
SIM800_DISCONNECTED
Network or Server is disconnected
SIM800_CONNECTED
Network or Server is connected
Definition at line 53 of file sim800_oper.h.
SIM800_HTTP_CMD
enum SIM800_HTTP_CMD
List of Command IDs for HTTP related commands
Enumerator
SIM800_HTTP_INIT
AT+HTTPINIT
SIM800_HTTP_PARA_CID
AT+HTTPPARA="CID",1
SIM800_HTTP_PARA_URL
AT+HTTPPARA="URL","you_url.whatever"
SIM800_HTTP_PARA_CTYPE
AT+HTTPPARA="CONTENT","type"
SIM800_HTTP_RQST_GET
AT+HTTPACTION=0
SIM800_HTTP_RQST_POST
AT+HTTPACTION=1
SIM800_HTTP_DATA_READ
AT+HTTPREAD
SIM800_HTTP_DATA_SEND
AT+HTTPDATA=x,y x:len int, y:timeout int
Definition at line 118 of file sim800_cmd_id.h.
SIM800_MOD_CMD
enum SIM800_MOD_CMD
List of Command IDs for SIM800 module related commands
Enumerator
SIM800_MOD_INIT
AT
SIM800_MOD_FCT_RST
AT&FZ
SIM800_MOD_TIME_FMT
AT+CLTS=1
SIM800_MOD_SAVE_NVM
AT&W
SIM800_MOD_DIS_FUNC
AT+CFUNC=0
SIM800_MOD_EN_FUNC
AT+CFUNC=1
SIM800_MOD_CHK_SIM
AT+CPIN?
SIM800_MOD_ECHO_OFF
ATE0
Definition at line 60 of file sim800_cmd_id.h.
SIM800_NET_CMD
enum SIM800_NET_CMD
List of Command IDs for Network related commands
Enumerator
SIM800_NET_CRT_CHK
AT+CREG?
SIM800_NET_BSET_CTYPE
AT+SAPBR=3,1,"Contype","GPRS"
SIM800_NET_BSET_APN
AT+SAPBR=3,1,"APN","apn"
SIM800_NET_BSET_USR
AT+SAPBR=3,1,"USER",""
SIM800_NET_BSET_PWD
AT+SAPBR=3,1,"PWD",""
SIM800_NET_BEN
AT+SAPBR=1,1
SIM800_NET_BCHK
AT+SAPBR=2,1
SIM800_NET_PDP_CNTX
AT+CGDCONT=1,"IP","apn"
SIM800_NET_ACTV_CID
AT+CGACT=1,1
SIM800_NET_EN_MUX
AT+CIPMUX=1
SIM800_NET_SEL_DTX
AT+CIPQSEND=1
SIM800_NET_TSK_START
AT+CSTT="apn","",""
SIM800_NET_EN_GPRS
AT+CIICR
SIM800_NET_GET_IP
AT+CIFSR
SIM800_NET_CHK
AT+CREG?
SIM800_NET_CHK_GPRS
AT+GATT?
Definition at line 81 of file sim800_cmd_id.h.
sim800_oper_http_contn_typ_t
enum sim800_oper_http_contn_typ_t
List of all the content types supported by this library
Enumerator
SIM800_HTTP_CONTENT_PTXT
Plain Text
SIM800_HTTP_CONTENT_RTXT
Rich Text
SIM800_HTTP_CONTENT_OCT_S
Octet stream
Definition at line 72 of file sim800_oper.h.
sim800_oper_status_t
enum sim800_oper_status_t
List of all possible status of SIM800 module
Enumerator
SIM800_IDLE
SIM800 present and idle
SIM800_BUSY
SIM800 present and executing a command
SIM800_HALT
SIM800 present and halted. Some critical command failed
SIM800_OVERLOAD
SIM800 present and overloaded. Number of commands exceeded the buffer length
SIM800_NOT_FOUND
SIM800 not present or not connected properly
Definition at line 36 of file sim800_oper.h.
sim800_operator_t
enum sim800_operator_t
For India
Note
JIO doesn't support 2G
Definition at line 63 of file sim800_oper.h.
sim800_req_type_t
enum sim800_req_type_t
List of HTTP request types
Definition at line 111 of file sim800_oper.h.
Function Documentation
sim800_oper_add_ticks()
void sim800_oper_add_ticks (uint32_t ticks)
The function to send Ticks to SIM800 module to keep common timebase.
Parameters
ticks Number of ticks since last add_tick event
Definition at line 1450 of file sim800_oper.c.
References AT_proc_add_ticks(), and AT_proc_is_busy().
sim800_oper_conns()
void sim800_oper_conns (sim800_server_conn_t * conn_params)
This function edits the AT command to required to connect to any server.
Parameters
conn_params Structure pointer to the structure to store connection parameters Return Connection ID when multiple Connections are needed.
Definition at line 1259 of file sim800_oper.c.
References sim800_server_conn_t::path_len, sim800_server_conn_t::path_ptr, sim800_server_conn_t::port_len, sim800_server_conn_t::port_ptr, sim800_server_conn_t::resource_len, sim800_server_conn_t::resource_ptr, and sim800_server_conn_t::server_ptr.
sim800_oper_enable_gprs()
void sim800_oper_enable_gprs (uint8_t * ip_addr, uint32_t * len)
This function push all the AT commands required to establish GPRS connection into the circular buffer.
Parameters
ip_addr Pointer to the memory where IP address is to be stored
len Pointer to the memory where length of IP address is to be stored
Definition at line 1063 of file sim800_oper.c.
References at_proc_cmd_t::cmd, at_proc_cmd_t::cmd_id, at_proc_cmd_t::err, IS_CMD_CRITICAL, at_proc_cmd_t::is_critical, at_proc_cmd_t::is_response_variable, IS_RSP_VARIABLE, at_uart_data_t::len, at_uart_data_t::ptr, at_proc_cmd_t::resp, SIM800_NET_ACTV_CID, SIM800_NET_BCHK, SIM800_NET_BEN, SIM800_NET_BSET_APN, SIM800_NET_BSET_CTYPE, SIM800_NET_BSET_PWD, SIM800_NET_BSET_USR, SIM800_NET_CRT_CHK, SIM800_NET_EN_GPRS, SIM800_NET_EN_MUX, SIM800_NET_GET_IP, SIM800_NET_PDP_CNTX, SIM800_NET_SEL_DTX, SIM800_NET_TSK_START, and at_proc_cmd_t::timeout.
sim800_oper_get_gprs_status()
sim800_conn_status_t sim800_oper_get_gprs_status ()
This function returns GPRS status.
Returns
GPRS connection status
Definition at line 1471 of file sim800_oper.c.
sim800_oper_get_status()
sim800_oper_status_t sim800_oper_get_status ()
This function returns SIM800 Operation module's status.
Returns
SIM800 status sim800_oper_status_t
Definition at line 1476 of file sim800_oper.c.
sim800_oper_http_req()
void sim800_oper_http_req (sim800_http_req_t * http_req)
This function edits and adds the AT commands required to make HTTP request.
Parameters
http_req Structure pointer to structure to store http request parameters.
Definition at line 1288 of file sim800_oper.c.
References at_proc_cmd_t::cmd, at_proc_cmd_t::cmd_id, sim800_http_req_t::content_type, at_proc_cmd_t::err, IS_CMD_CRITICAL, at_proc_cmd_t::is_critical, at_proc_cmd_t::is_response_variable, IS_RSP_VARIABLE, at_uart_data_t::len, sim800_http_req_t::p_received_data_handler, at_uart_data_t::ptr, sim800_http_req_t::req_type, at_proc_cmd_t::resp, SIM800_HTTP_INIT, SIM800_HTTP_PARA_CID, SIM800_HTTP_PARA_CTYPE, SIM800_HTTP_PARA_URL, and at_proc_cmd_t::timeout.
sim800_oper_init()
void sim800_oper_init (sim800_init_t * init)
This function add all the AT commands required to initialize the SIM800 hardware into circular buffer.
Parameters
init Structure pointer to the structure holding initialization information
Note
use to check if module is presented and connected properly
Refer sim800_oper.h for documentation
Definition at line 942 of file sim800_oper.c.
sim800_oper_process()
void sim800_oper_process ()
This function is to be called to perform background operations.
Note
it has to be called in while(true)
Definition at line 1425 of file sim800_oper.c.
References AT_proc_is_busy(), AT_proc_process(), AT_proc_send_cmd(), CBUF_Len, CBUF_Pop, and SIM800_IDLE.