Appiko: AT Process
AT Process
Codebase » AT Library
Driver to Process AT commands using hal_uarte module.
Data Structures
struct at_uart_data_t
struct at_proc_cmd_t
struct AT_proc_init_t
Enumerations
enum at_proc_cmd_check_t { AT_CMD_OK, AT_CMD_INVALID }
Functions
void AT_proc_init (AT_proc_init_t *init)
Function to initialize the AT command modules.
at_proc_cmd_check_t AT_proc_send_cmd (at_proc_cmd_t *cmd)
Function to send AT command.
void AT_proc_add_ticks (uint32_t ticks)
Function to handle add ticks event for AT command process module.
void AT_proc_process ()
Function to handle event and data generated at interrupt level at thread level.
uint8_t AT_proc_is_busy ()
Function to check if AT command process module is busy.
void AT_proc_repeat_last_cmd ()
Function to repeat the last instruction with same parameters.
void AT_proc_send_cmd_no_rsp (uint8_t *cmd, uint32_t len, uint32_t duration)
Function to execute an AT command where response is not needed.
Detailed Description
Warning
This module needs the device_tick and to be on and running to be able to work
Note
This module uses UARTE peripheral. So developer can't use uart prints for debugging
Enumeration Type Documentation
at_proc_cmd_check_t
enum at_proc_cmd_check_t
AT command sanity result
Enumerator
AT_CMD_OK
AT command terminated properly
AT_CMD_INVALID
AT command not terminated properly
Definition at line 48 of file AT_proc.h.
Function Documentation
AT_proc_add_ticks()
void AT_proc_add_ticks (uint32_t ticks)
The function to send Ticks to AT process module to keep common timebase.
Parameters
ticks Number of ticks since last add_tick event.
Definition at line 337 of file AT_proc.c.
References hal_uarte_puts().
Referenced by sim800_oper_add_ticks().
AT_proc_init()
void AT_proc_init (AT_proc_init_t * init)
This function saves the copy of function pointer.
Parameters
init Structure pointer to AT_Proc.
Refer AT_proc.h
Definition at line 277 of file AT_proc.c.
AT_proc_is_busy()
uint8_t AT_proc_is_busy ()
The function to check if module is busy.
Returns
1 if module is executing some AT command.
0 if module is available.
Definition at line 324 of file AT_proc.c.
Referenced by sim800_oper_add_ticks(), and sim800_oper_process().
AT_proc_process()
void AT_proc_process ()
This function is to be called to perform background operations.
Note
it has to be called in dependent module's process function.
Definition at line 318 of file AT_proc.c.
References hal_uarte_process().
Referenced by sim800_oper_process().
AT_proc_repeat_last_cmd()
void AT_proc_repeat_last_cmd ()
This function re-executes the last command again.
Definition at line 379 of file AT_proc.c.
AT_proc_send_cmd()
at_proc_cmd_check_t AT_proc_send_cmd (at_proc_cmd_t * cmd)
This function will send an AT command to the AT based hardware.
Parameters
cmd Structure pointer to structure which stores a AT command parameter.
Returns
Return AT_CMD_INVALID if AT command is not terminated properly.
Definition at line 286 of file AT_proc.c.
References AT_CMD_OK, at_proc_cmd_t::cmd, at_proc_cmd_t::cmd_id, hal_uarte_puts(), hal_uarte_start_rx(), at_proc_cmd_t::is_critical, at_proc_cmd_t::is_response_variable, at_uart_data_t::len, MS_TIMER_TICKS_MS, at_uart_data_t::ptr, and at_proc_cmd_t::timeout.
Referenced by sim800_oper_process().
AT_proc_send_cmd_no_rsp()
void AT_proc_send_cmd_no_rsp (uint8_t * cmd, uint32_t len, uint32_t duration)
The function to execute a AT command where no response is needed (data streaming).
Parameters
cmd Command string.
len Length of command string.
duration Duration for which module will be marked busy.
Note
This function don't care if operation was successful or not.
Definition at line 329 of file AT_proc.c.
References hal_uarte_puts(), and MS_TIMER_TICKS_MS.