var searchData=
[
  ['static_20and_20runtime_20assertion_3493',['Static and runtime assertion',['../group__group__assertion.html',1,'']]],
  ['softdevice_20event_20handler_3494',['Softdevice event handler',['../group__group__evt__sd__handler.html',1,'']]],
  ['saadc_20hal_3495',['SAADC HAL',['../group__group__saadc.html',1,'']]],
  ['softdevice_20assist_20libraries_3496',['SoftDevice Assist libraries',['../group__group__sd__assist.html',1,'']]],
  ['simple_20adc_20driver_3497',['Simple ADC driver',['../group__group__simple__adc.html',1,'']]],
  ['simple_20pwm_20driver_3498',['Simple PWM driver',['../group__group__simple__pwm.html',1,'']]],
  ['spi_20master_20hal_3499',['SPI Master HAL',['../group__group__spim__driver.html',1,'']]],
  ['sdk_20spirit_20management_20identification_20functions_3500',['SDK SPIRIT Management Identification Functions',['../group__IDENTIFICATION__FUNCTIONS.html',1,'']]],
  ['s2lp_20libraries_3501',['S2LP Libraries',['../group__S2LP__Libraries.html',1,'']]],
  ['spi_20driver_3502',['SPI Driver',['../group__S2LP__SPI__Driver.html',1,'']]],
  ['saadc_20logger_3503',['SAADC Logger',['../group__saadc__logger.html',1,'']]],
  ['sdk_20basic_20generic_3504',['SDK Basic Generic',['../group__SDK__Basic__Generic.html',1,'']]],
  ['sdk_20basic_20generic_20a_3505',['SDK Basic Generic A',['../group__SDK__Basic__Generic__A.html',1,'']]],
  ['sdk_20basic_20generic_20b_3506',['SDK Basic Generic B',['../group__SDK__Basic__Generic__B.html',1,'']]],
  ['sdk_20eeprom_20management_3507',['SDK EEPROM Management',['../group__SDK__EEPROM.html',1,'']]],
  ['sdk_20eval_20button_3508',['SDK EVAL Button',['../group__SDK__EVAL__Button.html',1,'']]],
  ['sdk_20eval_20button_20exported_20constants_3509',['SDK EVAL Button Exported Constants',['../group__SDK__EVAL__Button__Exported__Constants.html',1,'']]],
  ['sdk_20eval_20button_20exported_20functions_3510',['SDK EVAL Button Exported Functions',['../group__SDK__EVAL__Button__Exported__Functions.html',1,'']]],
  ['sdk_20eval_20button_20exported_20macros_3511',['SDK EVAL Button Exported Macros',['../group__SDK__EVAL__Button__Exported__Macros.html',1,'']]],
  ['sdk_20eval_20button_20exported_20types_3512',['SDK EVAL Button Exported Types',['../group__SDK__EVAL__Button__Exported__Types.html',1,'']]],
  ['sdk_20eval_20button_20private_20defines_3513',['SDK EVAL Button Private Defines',['../group__SDK__EVAL__Button__Private__Defines.html',1,'']]],
  ['sdk_20eval_20button_20private_20function_20prototypes_3514',['SDK EVAL Button Private Function Prototypes',['../group__SDK__EVAL__Button__Private__FunctionPrototypes.html',1,'']]],
  ['sdk_20eval_20button_20private_20functions_3515',['SDK EVAL Button Private Functions',['../group__SDK__EVAL__Button__Private__Functions.html',1,'']]],
  ['sdk_20eval_20button_20private_20macros_3516',['SDK EVAL Button Private Macros',['../group__SDK__EVAL__Button__Private__Macros.html',1,'']]],
  ['sdk_20eval_20button_20private_20types_20definitions_3517',['SDK EVAL Button Private Types Definitions',['../group__SDK__EVAL__Button__Private__TypesDefinitions.html',1,'']]],
  ['sdk_20eval_20com_3518',['SDK EVAL Com',['../group__SDK__EVAL__Com.html',1,'']]],
  ['sdk_20eval_20com_20exported_20functions_3519',['SDK EVAL Com Exported Functions',['../group__SDK__EVAL__Com__Exported__Functions.html',1,'']]],
  ['sdk_20eval_20com_20exported_20types_3520',['SDK EVAL Com Exported Types',['../group__SDK__EVAL__Com__Exported__Types.html',1,'']]],
  ['sdk_20eval_20com_20private_20defines_3521',['SDK EVAL Com Private Defines',['../group__SDK__EVAL__Com__Private__Defines.html',1,'']]],
  ['sdk_20eval_20com_20private_20functions_3522',['SDK EVAL Com Private Functions',['../group__SDK__EVAL__Com__Private__Functions.html',1,'']]],
  ['sdk_20eval_20com_20private_20macros_3523',['SDK EVAL Com Private Macros',['../group__SDK__EVAL__Com__Private__Macros.html',1,'']]],
  ['sdk_20eval_20com_20private_20types_20definitions_3524',['SDK EVAL Com Private Types Definitions',['../group__SDK__EVAL__Com__Private__TypesDefinitions.html',1,'']]],
  ['sdk_20eval_20com_20private_20variables_3525',['SDK EVAL Com Private Variables',['../group__SDK__EVAL__Com__Private__Variables.html',1,'']]],
  ['sdk_20eval_20config_3526',['SDK EVAL Config',['../group__SDK__EVAL__Config.html',1,'']]],
  ['sdk_20eval_20config_20exported_20constants_3527',['SDK EVAL Config Exported Constants',['../group__SDK__EVAL__Config__Exported__Constants.html',1,'']]],
  ['sdk_20eval_20config_20exported_20functions_3528',['SDK EVAL Config Exported Functions',['../group__SDK__EVAL__Config__Exported__Functions.html',1,'']]],
  ['sdk_20eval_20config_20private_20defines_3529',['SDK EVAL Config Private Defines',['../group__SDK__EVAL__Config__Private__Defines.html',1,'']]],
  ['sdk_20eval_20config_20private_20function_20prototypes_3530',['SDK EVAL Config Private Function Prototypes',['../group__SDK__EVAL__Config__Private__FunctionPrototypes.html',1,'']]],
  ['sdk_20eval_20config_20private_20functions_3531',['SDK EVAL Config Private Functions',['../group__SDK__EVAL__Config__Private__Functions.html',1,'']]],
  ['sdk_20eval_20config_20private_20macros_3532',['SDK EVAL Config Private Macros',['../group__SDK__EVAL__Config__Private__Macros.html',1,'']]],
  ['sdk_20eval_20config_20private_20types_20definitions_3533',['SDK EVAL Config Private Types Definitions',['../group__SDK__EVAL__Config__Private__TypesDefinitions.html',1,'']]],
  ['sdk_20eval_20config_20private_20variables_3534',['SDK EVAL Config Private Variables',['../group__SDK__EVAL__Config__Private__Variables.html',1,'']]],
  ['sdk_20eval_20gpio_3535',['SDK EVAL Gpio',['../group__SDK__EVAL__Gpio.html',1,'']]],
  ['sdk_20eval_20gpio_20exported_20constants_3536',['SDK EVAL Gpio Exported Constants',['../group__SDK__EVAL__Gpio__Exported__Constants.html',1,'']]],
  ['sdk_20eval_20gpio_20exported_20functions_3537',['SDK EVAL Gpio Exported Functions',['../group__SDK__EVAL__Gpio__Exported__Functions.html',1,'']]],
  ['sdk_20eval_20gpio_20exported_20macros_3538',['SDK EVAL Gpio Exported Macros',['../group__SDK__EVAL__Gpio__Exported__Macros.html',1,'']]],
  ['sdk_20eval_20gpio_20exported_20types_3539',['SDK EVAL Gpio Exported Types',['../group__SDK__EVAL__Gpio__Exported__Types.html',1,'']]],
  ['sdk_20eval_20gpio_20private_20functions_3540',['SDK EVAL Gpio Private Functions',['../group__SDK__EVAL__Gpio__Private__Functions.html',1,'']]],
  ['sdk_20eval_20gpio_20private_20variables_3541',['SDK EVAL Gpio Private Variables',['../group__SDK__EVAL__Gpio__Private__Variables.html',1,'']]],
  ['sdk_20eval_20led_3542',['SDK EVAL Led',['../group__SDK__EVAL__Led.html',1,'']]],
  ['sdk_20eval_20led_20exported_20constants_3543',['SDK EVAL Led Exported Constants',['../group__SDK__EVAL__Led__Exported__Constants.html',1,'']]],
  ['sdk_20eval_20led_20exported_20functions_3544',['SDK EVAL Led Exported Functions',['../group__SDK__EVAL__Led__Exported__Functions.html',1,'']]],
  ['sdk_20eval_20led_20exported_20macros_3545',['SDK EVAL Led Exported Macros',['../group__SDK__EVAL__Led__Exported__Macros.html',1,'']]],
  ['sdk_20eval_20led_20exported_20types_3546',['SDK EVAL Led Exported Types',['../group__SDK__EVAL__Led__Exported__Types.html',1,'']]],
  ['sdk_20eval_20led_20private_20defines_3547',['SDK EVAL Led Private Defines',['../group__SDK__EVAL__Led__Private__Defines.html',1,'']]],
  ['sdk_20eval_20led_20private_20function_20prototypes_3548',['SDK EVAL Led Private Function Prototypes',['../group__SDK__EVAL__Led__Private__FunctionPrototypes.html',1,'']]],
  ['sdk_20eval_20led_20private_20functions_3549',['SDK EVAL Led Private Functions',['../group__SDK__EVAL__Led__Private__Functions.html',1,'']]],
  ['sdk_20eval_20led_20private_20macros_3550',['SDK EVAL Led Private Macros',['../group__SDK__EVAL__Led__Private__Macros.html',1,'']]],
  ['sdk_20eval_20led_20private_20types_20definitions_3551',['SDK EVAL Led Private Types Definitions',['../group__SDK__EVAL__Led__Private__TypesDefinitions.html',1,'']]],
  ['sdk_20eval_20led_20private_20variables_3552',['SDK EVAL Led Private Variables',['../group__SDK__EVAL__Led__Private__Variables.html',1,'']]],
  ['sdk_2deval_20nucleo_3553',['SDK-EVAL NUCLEO',['../group__SDK__EVAL__NUCLEO.html',1,'']]],
  ['sdk_20eval_20spi_3554',['SDK EVAL Spi',['../group__SDK__EVAL__Spi.html',1,'']]],
  ['sdk_5feval_5fspi_5fperipheral_5fgpio_3555',['SDK_EVAL_Spi_Peripheral_Gpio',['../group__SDK__EVAL__Spi__Peripheral__Gpio.html',1,'']]],
  ['sdk_20examples_3556',['SDK Examples',['../group__SDK__Examples.html',1,'']]],
  ['sdk_20spirit_20management_3557',['SDK SPIRIT Management',['../group__SDK__SPIRIT__MANAGEMENT.html',1,'']]],
  ['sdk_20spirit_20management_20functions_3558',['SDK SPIRIT Management Functions',['../group__SDK__SPIRIT__MANAGEMENT__FUNCTIONS.html',1,'']]],
  ['spi_20exported_20constants_3559',['SPI Exported Constants',['../group__SPI__Exported__Constants.html',1,'']]],
  ['spi_20exported_20functions_3560',['SPI Exported Functions',['../group__SPI__Exported__Functions.html',1,'']]],
  ['spi_20exported_20macros_3561',['SPI Exported Macros',['../group__SPI__Exported__Macros.html',1,'']]],
  ['spi_20exported_20types_3562',['SPI Exported Types',['../group__SPI__Exported__Types.html',1,'']]],
  ['spi_5fheaders_3563',['SPI_Headers',['../group__SPI__Headers.html',1,'']]],
  ['spi_5fprivate_5fdefines_3564',['SPI_Private_Defines',['../group__SPI__Private__Defines.html',1,'']]],
  ['spi_5fprivate_5ffunctionprototypes_3565',['SPI_Private_FunctionPrototypes',['../group__SPI__Private__FunctionPrototypes.html',1,'']]],
  ['spi_5fprivate_5ffunctions_3566',['SPI_Private_Functions',['../group__SPI__Private__Functions.html',1,'']]],
  ['spi_5fprivate_5fmacros_3567',['SPI_Private_Macros',['../group__SPI__Private__Macros.html',1,'']]],
  ['spi_5fprivate_5fvariables_3568',['SPI_Private_Variables',['../group__SPI__Private__Variables.html',1,'']]],
  ['spirit_20dk_3569',['SPIRIT DK',['../group__SPIRIT__DK.html',1,'']]],
  ['system_20level_20testing_20application_20for_20sense_20rev4_20board_3570',['System level testing application for Sense Rev4 board',['../group__sys__lvl__testing.html',1,'']]]
];
